package com.delacrixmorgan.kingscup.ui.theme.color

import androidx.compose.ui.graphics.Color

data object EmeraldColorPreference : ColorPreference(
    // Light
    primaryLight = Color(0xFF5A614D),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFF8FFE5),
    onPrimaryContainerLight = Color(0xFF6F7762),
    secondaryLight = Color(0xFF006C4F),
    onSecondaryLight = Color(0xFFFFFFFF),
    secondaryContainerLight = Color(0xFF06D6A0),
    onSecondaryContainerLight = Color(0xFF00573F),
    tertiaryLight = Color(0xFF576156),
    onTertiaryLight = Color(0xFFFFFFFF),
    tertiaryContainerLight = Color(0xFFF4FFF1),
    onTertiaryContainerLight = Color(0xFF6C776B),
    errorLight = Color(0xFFBA1A1A),
    onErrorLight = Color(0xFFFFFFFF),
    errorContainerLight = Color(0xFFFFDAD6),
    onErrorContainerLight = Color(0xFF93000A),
    backgroundLight = Color(0xFFFCF9F5),
    onBackgroundLight = Color(0xFF1C1C1A),
    surfaceLight = Color(0xFFFCF9F5),
    onSurfaceLight = Color(0xFF1C1C1A),
    surfaceVariantLight = Color(0xFFE3E3D9),
    onSurfaceVariantLight = Color(0xFF464840),
    outlineLight = Color(0xFF76786F),
    outlineVariantLight = Color(0xFFC6C7BD),
    scrimLight = Color(0xFF000000),
    inverseSurfaceLight = Color(0xFF31302E),
    inverseOnSurfaceLight = Color(0xFFF3F0ED),
    inversePrimaryLight = Color(0xFFC2C9B1),
    surfaceDimLight = Color(0xFFDCDAD6),
    surfaceBrightLight = Color(0xFFFCF9F5),
    surfaceContainerLowestLight = Color(0xFFFFFFFF),
    surfaceContainerLowLight = Color(0xFFF6F3F0),
    surfaceContainerLight = Color(0xFFF0EDEA),
    surfaceContainerHighLight = Color(0xFFEBE8E4),
    surfaceContainerHighestLight = Color(0xFFE5E2DF),

    // Dark
    primaryDark = Color(0xFFFFFFFF),
    onPrimaryDark = Color(0xFF2C3322),
    primaryContainerDark = Color(0xFFDEE6CC),
    onPrimaryContainerDark = Color(0xFF606753),
    secondaryDark = Color(0xFF47F3BB),
    onSecondaryDark = Color(0xFF003827),
    secondaryContainerDark = Color(0xFF06D6A0),
    onSecondaryContainerDark = Color(0xFF00573F),
    tertiaryDark = Color(0xFFFFFFFF),
    onTertiaryDark = Color(0xFF29332A),
    tertiaryContainerDark = Color(0xFFDBE6D8),
    onTertiaryContainerDark = Color(0xFF5D675C),
    errorDark = Color(0xFFFFB4AB),
    onErrorDark = Color(0xFF690005),
    errorContainerDark = Color(0xFF93000A),
    onErrorContainerDark = Color(0xFFFFDAD6),
    backgroundDark = Color(0xFF131312),
    onBackgroundDark = Color(0xFFE5E2DF),
    surfaceDark = Color(0xFF131312),
    onSurfaceDark = Color(0xFFE5E2DF),
    surfaceVariantDark = Color(0xFF464840),
    onSurfaceVariantDark = Color(0xFFC6C7BD),
    outlineDark = Color(0xFF909188),
    outlineVariantDark = Color(0xFF464840),
    scrimDark = Color(0xFF000000),
    inverseSurfaceDark = Color(0xFFE5E2DF),
    inverseOnSurfaceDark = Color(0xFF31302E),
    inversePrimaryDark = Color(0xFF5A614D),
    surfaceDimDark = Color(0xFF131312),
    surfaceBrightDark = Color(0xFF393937),
    surfaceContainerLowestDark = Color(0xFF0E0E0D),
    surfaceContainerLowDark = Color(0xFF1C1C1A),
    surfaceContainerDark = Color(0xFF20201E),
    surfaceContainerHighDark = Color(0xFF2A2A28),
    surfaceContainerHighestDark = Color(0xFF353533),
)