package com.delacrixmorgan.kingscup.ui.theme.color

import androidx.compose.ui.graphics.Color

data object MadderColorPreference : ColorPreference(
    // Light
    primaryLight = Color(0xFF605E5F),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFFCF7F8),
    onPrimaryContainerLight = Color(0xFF747172),
    secondaryLight = Color(0xFF7D0011),
    onSecondaryLight = Color(0xFFFFFFFF),
    secondaryContainerLight = Color(0xFFA31621),
    onSecondaryContainerLight = Color(0xFFFFB2AE),
    tertiaryLight = Color(0xFF615D5E),
    onTertiaryLight = Color(0xFFFFFFFF),
    tertiaryContainerLight = Color(0xFFFEF7F7),
    onTertiaryContainerLight = Color(0xFF757171),
    errorLight = Color(0xFFBA1A1A),
    onErrorLight = Color(0xFFFFFFFF),
    errorContainerLight = Color(0xFFFFDAD6),
    onErrorContainerLight = Color(0xFF93000A),
    backgroundLight = Color(0xFFFDF8F8),
    onBackgroundLight = Color(0xFF1C1B1B),
    surfaceLight = Color(0xFFFDF8F8),
    onSurfaceLight = Color(0xFF1C1B1B),
    surfaceVariantLight = Color(0xFFE7E1E6),
    onSurfaceVariantLight = Color(0xFF49464A),
    outlineLight = Color(0xFF7A767A),
    outlineVariantLight = Color(0xFFCAC5CA),
    scrimLight = Color(0xFF000000),
    inverseSurfaceLight = Color(0xFF313030),
    inverseOnSurfaceLight = Color(0xFFF4F0EF),
    inversePrimaryLight = Color(0xFFCAC5C6),
    surfaceDimLight = Color(0xFFDDD9D9),
    surfaceBrightLight = Color(0xFFFDF8F8),
    surfaceContainerLowestLight = Color(0xFFFFFFFF),
    surfaceContainerLowLight = Color(0xFFF7F3F2),
    surfaceContainerLight = Color(0xFFF1EDEC),
    surfaceContainerHighLight = Color(0xFFEBE7E7),
    surfaceContainerHighestLight = Color(0xFFE6E2E1),

    // Dark
    primaryDark = Color(0xFFFFFFFF),
    onPrimaryDark = Color(0xFF313031),
    primaryContainerDark = Color(0xFFE6E1E2),
    onPrimaryContainerDark = Color(0xFF666465),
    secondaryDark = Color(0xFFFFB3AE),
    onSecondaryDark = Color(0xFF68000D),
    secondaryContainerDark = Color(0xFFA31621),
    onSecondaryContainerDark = Color(0xFFFFB2AE),
    tertiaryDark = Color(0xFFFFFFFF),
    onTertiaryDark = Color(0xFF333030),
    tertiaryContainerDark = Color(0xFFE7E1E1),
    onTertiaryContainerDark = Color(0xFF676364),
    errorDark = Color(0xFFFFB4AB),
    onErrorDark = Color(0xFF690005),
    errorContainerDark = Color(0xFF93000A),
    onErrorContainerDark = Color(0xFFFFDAD6),
    backgroundDark = Color(0xFF141313),
    onBackgroundDark = Color(0xFFE6E2E1),
    surfaceDark = Color(0xFF141313),
    onSurfaceDark = Color(0xFFE6E2E1),
    surfaceVariantDark = Color(0xFF49464A),
    onSurfaceVariantDark = Color(0xFFCAC5CA),
    outlineDark = Color(0xFF948F94),
    outlineVariantDark = Color(0xFF49464A),
    scrimDark = Color(0xFF000000),
    inverseSurfaceDark = Color(0xFFE6E2E1),
    inverseOnSurfaceDark = Color(0xFF313030),
    inversePrimaryDark = Color(0xFF605E5F),
    surfaceDimDark = Color(0xFF141313),
    surfaceBrightDark = Color(0xFF3A3939),
    surfaceContainerLowestDark = Color(0xFF0F0E0E),
    surfaceContainerLowDark = Color(0xFF1C1B1B),
    surfaceContainerDark = Color(0xFF201F1F),
    surfaceContainerHighDark = Color(0xFF2B2A2A),
    surfaceContainerHighestDark = Color(0xFF363434),
)