package com.delacrixmorgan.kingscup.theme.color

import androidx.compose.ui.graphics.Color

data object BoraColorPreference : ColorPreference(
    // Light
    primaryLight = Color(0xFF5E6143),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFEAECC6),
    onPrimaryContainerLight = Color(0xFF686B4C),
    secondaryLight = Color(0xFF00677D),
    onSecondaryLight = Color(0xFFFFFFFF),
    secondaryContainerLight = Color(0xFF2BC0E4),
    onSecondaryContainerLight = Color(0xFF004A5B),
    tertiaryLight = Color(0xFF506351),
    onTertiaryLight = Color(0xFFFFFFFF),
    tertiaryContainerLight = Color(0xFFD9EFD8),
    onTertiaryContainerLight = Color(0xFF5A6D5B),
    errorLight = Color(0xFFBA1A1A),
    onErrorLight = Color(0xFFFFFFFF),
    errorContainerLight = Color(0xFFFFDAD6),
    onErrorContainerLight = Color(0xFF93000A),
    backgroundLight = Color(0xFFFCF9F4),
    onBackgroundLight = Color(0xFF1C1C19),
    surfaceLight = Color(0xFFFCF9F4),
    onSurfaceLight = Color(0xFF1C1C19),
    surfaceVariantLight = Color(0xFFE5E3D6),
    onSurfaceVariantLight = Color(0xFF47473E),
    outlineLight = Color(0xFF78786D),
    outlineVariantLight = Color(0xFFC8C7BA),
    scrimLight = Color(0xFF000000),
    inverseSurfaceLight = Color(0xFF31302E),
    inverseOnSurfaceLight = Color(0xFFF4F0EC),
    inversePrimaryLight = Color(0xFFC7C9A5),
    surfaceDimLight = Color(0xFFDDD9D5),
    surfaceBrightLight = Color(0xFFFCF9F4),
    surfaceContainerLowestLight = Color(0xFFFFFFFF),
    surfaceContainerLowLight = Color(0xFFF7F3EE),
    surfaceContainerLight = Color(0xFFF1EDE9),
    surfaceContainerHighLight = Color(0xFFEBE8E3),
    surfaceContainerHighestLight = Color(0xFFE5E2DD),

    // Dark
    primaryDark = Color(0xFFFFFFFF),
    onPrimaryDark = Color(0xFF303219),
    primaryContainerDark = Color(0xFFE3E5C0),
    onPrimaryContainerDark = Color(0xFF646749),
    secondaryDark = Color(0xFF5EDBFF),
    onSecondaryDark = Color(0xFF003642),
    secondaryContainerDark = Color(0xFF2BC0E4),
    onSecondaryContainerDark = Color(0xFF004A5B),
    tertiaryDark = Color(0xFFFFFFFF),
    onTertiaryDark = Color(0xFF233525),
    tertiaryContainerDark = Color(0xFFD2E8D2),
    onTertiaryContainerDark = Color(0xFF566957),
    errorDark = Color(0xFFFFB4AB),
    onErrorDark = Color(0xFF690005),
    errorContainerDark = Color(0xFF93000A),
    onErrorContainerDark = Color(0xFFFFDAD6),
    backgroundDark = Color(0xFF141311),
    onBackgroundDark = Color(0xFFE5E2DD),
    surfaceDark = Color(0xFF141311),
    onSurfaceDark = Color(0xFFE5E2DD),
    surfaceVariantDark = Color(0xFF47473E),
    onSurfaceVariantDark = Color(0xFFC8C7BA),
    outlineDark = Color(0xFF929186),
    outlineVariantDark = Color(0xFF47473E),
    scrimDark = Color(0xFF000000),
    inverseSurfaceDark = Color(0xFFE5E2DD),
    inverseOnSurfaceDark = Color(0xFF31302E),
    inversePrimaryDark = Color(0xFF5E6143),
    surfaceDimDark = Color(0xFF141311),
    surfaceBrightDark = Color(0xFF3A3936),
    surfaceContainerLowestDark = Color(0xFF0E0E0C),
    surfaceContainerLowDark = Color(0xFF1C1C19),
    surfaceContainerDark = Color(0xFF20201D),
    surfaceContainerHighDark = Color(0xFF2A2A27),
    surfaceContainerHighestDark = Color(0xFF353532),
)