package com.delacrixmorgan.kingscup.theme.color

import androidx.compose.ui.graphics.Color

data object ClassicColorPreference : ColorPreference(
    // Light
    primaryLight = Color(0xFF121D38),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFF28324E),
    onPrimaryContainerLight = Color(0xFF909ABC),
    secondaryLight = Color(0xFFB70052),
    onSecondaryLight = Color(0xFFFFFFFF),
    secondaryContainerLight = Color(0xFFDD2269),
    onSecondaryContainerLight = Color(0xFFFFFBFF),
    tertiaryLight = Color(0xFF695F00),
    onTertiaryLight = Color(0xFFFFFFFF),
    tertiaryContainerLight = Color(0xFFFFEB3B),
    onTertiaryContainerLight = Color(0xFF746900),
    errorLight = Color(0xFFBA1A1A),
    onErrorLight = Color(0xFFFFFFFF),
    errorContainerLight = Color(0xFFFFDAD6),
    onErrorContainerLight = Color(0xFF93000A),
    backgroundLight = Color(0xFFFBF8FB),
    onBackgroundLight = Color(0xFF1B1B1E),
    surfaceLight = Color(0xFFFBF8FB),
    onSurfaceLight = Color(0xFF1B1B1E),
    surfaceVariantLight = Color(0xFFE2E2EA),
    onSurfaceVariantLight = Color(0xFF45464D),
    outlineLight = Color(0xFF76777E),
    outlineVariantLight = Color(0xFFC6C6CE),
    scrimLight = Color(0xFF000000),
    inverseSurfaceLight = Color(0xFF303032),
    inverseOnSurfaceLight = Color(0xFFF3F0F3),
    inversePrimaryLight = Color(0xFFBCC6E9),
    surfaceDimLight = Color(0xFFDCD9DC),
    surfaceBrightLight = Color(0xFFFBF8FB),
    surfaceContainerLowestLight = Color(0xFFFFFFFF),
    surfaceContainerLowLight = Color(0xFFF6F3F5),
    surfaceContainerLight = Color(0xFFF0EDF0),
    surfaceContainerHighLight = Color(0xFFEAE7EA),
    surfaceContainerHighestLight = Color(0xFFE4E2E4),

    // Dark
    primaryDark = Color(0xFFBCC6E9),
    onPrimaryDark = Color(0xFF25304B),
    primaryContainerDark = Color(0xFF28324E),
    onPrimaryContainerDark = Color(0xFF909ABC),
    secondaryDark = Color(0xFFFFB1C1),
    onSecondaryDark = Color(0xFF66002A),
    secondaryContainerDark = Color(0xFFFF4C86),
    onSecondaryContainerDark = Color(0xFF530021),
    tertiaryDark = Color(0xFFFFFFFF),
    onTertiaryDark = Color(0xFF363100),
    tertiaryContainerDark = Color(0xFFF9E534),
    onTertiaryContainerDark = Color(0xFF706500),
    errorDark = Color(0xFFFFB4AB),
    onErrorDark = Color(0xFF690005),
    errorContainerDark = Color(0xFF93000A),
    onErrorContainerDark = Color(0xFFFFDAD6),
    backgroundDark = Color(0xFF131315),
    onBackgroundDark = Color(0xFFE4E2E4),
    surfaceDark = Color(0xFF131315),
    onSurfaceDark = Color(0xFFE4E2E4),
    surfaceVariantDark = Color(0xFF45464D),
    onSurfaceVariantDark = Color(0xFFC6C6CE),
    outlineDark = Color(0xFF909098),
    outlineVariantDark = Color(0xFF45464D),
    scrimDark = Color(0xFF000000),
    inverseSurfaceDark = Color(0xFFE4E2E4),
    inverseOnSurfaceDark = Color(0xFF303032),
    inversePrimaryDark = Color(0xFF545E7C),
    surfaceDimDark = Color(0xFF131315),
    surfaceBrightDark = Color(0xFF39393B),
    surfaceContainerLowestDark = Color(0xFF0E0E10),
    surfaceContainerLowDark = Color(0xFF1B1B1E),
    surfaceContainerDark = Color(0xFF1F1F22),
    surfaceContainerHighDark = Color(0xFF2A2A2C),
    surfaceContainerHighestDark = Color(0xFF353437),
)