package com.delacrixmorgan.kingscup.theme.color

import androidx.compose.ui.graphics.Color

data object SandColorPreference : ColorPreference(
    // Light
    primaryLight = Color(0xFF904A41),
    onPrimaryLight = Color(0xFFFFFFFF),
    primaryContainerLight = Color(0xFFFFDAD5),
    onPrimaryContainerLight = Color(0xFF73342C),
    secondaryLight = Color(0xFF3F5F90),
    onSecondaryLight = Color(0xFFFFFFFF),
    secondaryContainerLight = Color(0xFFD5E3FF),
    onSecondaryContainerLight = Color(0xFF254777),
    tertiaryLight = Color(0xFF705C2E),
    onTertiaryLight = Color(0xFFFFFFFF),
    tertiaryContainerLight = Color(0xFFFCDFA6),
    onTertiaryContainerLight = Color(0xFF574419),
    errorLight = Color(0xFFBA1A1A),
    onErrorLight = Color(0xFFFFFFFF),
    errorContainerLight = Color(0xFFFFDAD6),
    onErrorContainerLight = Color(0xFF93000A),
    backgroundLight = Color(0xFFFFF8F7),
    onBackgroundLight = Color(0xFF231918),
    surfaceLight = Color(0xFFFFF8F7),
    onSurfaceLight = Color(0xFF231918),
    surfaceVariantLight = Color(0xFFF5DDDA),
    onSurfaceVariantLight = Color(0xFF534341),
    outlineLight = Color(0xFF857370),
    outlineVariantLight = Color(0xFFD8C2BE),
    scrimLight = Color(0xFF000000),
    inverseSurfaceLight = Color(0xFF392E2C),
    inverseOnSurfaceLight = Color(0xFFFFEDEA),
    inversePrimaryLight = Color(0xFFFFB4A9),
    surfaceDimLight = Color(0xFFE8D6D3),
    surfaceBrightLight = Color(0xFFFFF8F7),
    surfaceContainerLowestLight = Color(0xFFFFFFFF),
    surfaceContainerLowLight = Color(0xFFFFF0EE),
    surfaceContainerLight = Color(0xFFFCEAE7),
    surfaceContainerHighLight = Color(0xFFF7E4E1),
    surfaceContainerHighestLight = Color(0xFFF1DEDC),

    // Dark
    primaryDark = Color(0xFFFFB4A9),
    onPrimaryDark = Color(0xFF561E18),
    primaryContainerDark = Color(0xFF73342C),
    onPrimaryContainerDark = Color(0xFFFFDAD5),
    secondaryDark = Color(0xFFA8C8FF),
    onSecondaryDark = Color(0xFF06305F),
    secondaryContainerDark = Color(0xFF254777),
    onSecondaryContainerDark = Color(0xFFD5E3FF),
    tertiaryDark = Color(0xFFDFC38C),
    onTertiaryDark = Color(0xFF3E2E04),
    tertiaryContainerDark = Color(0xFF574419),
    onTertiaryContainerDark = Color(0xFFFCDFA6),
    errorDark = Color(0xFFFFB4AB),
    onErrorDark = Color(0xFF690005),
    errorContainerDark = Color(0xFF93000A),
    onErrorContainerDark = Color(0xFFFFDAD6),
    backgroundDark = Color(0xFF1A1110),
    onBackgroundDark = Color(0xFFF1DEDC),
    surfaceDark = Color(0xFF1A1110),
    onSurfaceDark = Color(0xFFF1DEDC),
    surfaceVariantDark = Color(0xFF534341),
    onSurfaceVariantDark = Color(0xFFD8C2BE),
    outlineDark = Color(0xFFA08C89),
    outlineVariantDark = Color(0xFF534341),
    scrimDark = Color(0xFF000000),
    inverseSurfaceDark = Color(0xFFF1DEDC),
    inverseOnSurfaceDark = Color(0xFF392E2C),
    inversePrimaryDark = Color(0xFF904A41),
    surfaceDimDark = Color(0xFF1A1110),
    surfaceBrightDark = Color(0xFF423735),
    surfaceContainerLowestDark = Color(0xFF140C0B),
    surfaceContainerLowDark = Color(0xFF231918),
    surfaceContainerDark = Color(0xFF271D1C),
    surfaceContainerHighDark = Color(0xFF322826),
    surfaceContainerHighestDark = Color(0xFF3D3231),
)